version: '3'
services:
  dbpostgresql_cards:
    container_name: "cards_db"
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: cardsDb
